package com.zerobias.module.x12.codegen.model;

import java.util.ArrayList;
import java.util.List;

/**
 * One content pack's manifest entry, as emitted into {@code packs.json} (DESIGN §7).
 *
 * <p>A pack is the unit of content delivery: a guide's schema tree and structure index, the
 * code-set enums, or the receiver's own shared schemas. The manifest shape is the same
 * whichever way a pack arrives — {@code bundled} here (generated by this package and baked
 * into the image), or later {@code npm}/{@code uploaded} — so the loader has one code path
 * and {@code ops/packs} can report provenance.
 *
 * <p>{@code version} is null for bundled packs: their version IS the module's, so reporting
 * a second one would just be a thing to keep in sync. External packs carry their own.
 */
public final class Pack {

    /** How the pack reached the module. Bundled packs are the floor: always present, never removable. */
    public static final String SOURCE_BUNDLED = "bundled";

    public String name;
    public String namespace;
    public String source;
    public String version;
    /** The guide this pack covers ({@code null} for the codes/core packs). */
    public String gs08;
    /** Set when {@code gs08} is an alias of another guide's canonical id. */
    public String aliasOf;
    public String transactionType;
    /** Relative path of this pack's structure index, or null when it has none. */
    public String structureIndex;
    /**
     * Human-readable scope of the ids this pack owns, e.g. {@code x12.005010X221A1.*}. For
     * reporting only: {@link #schemaIds} is the authoritative ownership record, so the
     * loader's collision check is exact rather than a prefix guess (a guide pack owns both
     * {@code schema:type:…} and its {@code schema:table:…} id, which share no prefix).
     */
    public String idScope;
    public int schemaCount;
    /** Schema ids owned by the pack, in emission order. */
    public List<String> schemaIds = new ArrayList<>();

    public Pack(String name, String namespace, String idScope) {
        this.name = name;
        this.namespace = namespace;
        this.idScope = idScope;
        this.source = SOURCE_BUNDLED;
    }

    public Pack guide(String gs08, String aliasOf, String transactionType, String structureIndex) {
        this.gs08 = gs08;
        this.aliasOf = aliasOf;
        this.transactionType = transactionType;
        this.structureIndex = structureIndex;
        return this;
    }

    public void add(String schemaId) {
        schemaIds.add(schemaId);
        schemaCount = schemaIds.size();
    }
}
