package com.zerobias.module.x12.producer;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The content packs this module has loaded (DESIGN §7).
 *
 * <p>A pack is the unit of content delivery: one X12 guide's schema tree plus its structure
 * index, the code-set enums, or the receiver's own shared schemas. Packs generated by this
 * package are baked into the image and described by {@code packs.json} on the classpath —
 * {@code source: bundled}. The manifest shape is deliberately the same one an
 * npm-delivered or uploaded pack will carry, so adding those later means pointing this
 * loader at another root, not writing a second code path.
 *
 * <p>Bundled packs are the floor: always present, never removable, and nothing may
 * supersede {@code x12-core} (the module's own contract rather than content).
 *
 * <p>Absent or malformed {@code packs.json} yields an empty catalog and a warning, never a
 * boot failure — an always-on receiver must still ingest files if only its provenance
 * reporting is broken.
 */
public final class PackCatalog {

    private static final Logger LOG = LoggerFactory.getLogger(PackCatalog.class);
    private static final Gson GSON = new Gson();
    private static final String RESOURCE = "packs.json";

    /** The core pack: the module's own schemas, not content. */
    public static final String CORE_PACK = "x12-core";

    /** One pack's manifest, plus what the registry actually resolved for it. */
    public record Pack(String name, String namespace, String source, String version, String gs08,
            String aliasOf, String transactionType, String structureIndex, String idScope,
            int schemaCount, List<String> schemaIds) {

        public Pack {
            schemaIds = schemaIds == null ? List.of() : List.copyOf(schemaIds);
        }

        /** Whether this pack is the module's own contract (never superseded, never removed). */
        public boolean core() {
            return CORE_PACK.equals(name);
        }

        /** The schema ids this pack declares but the registry cannot serve. */
        public List<String> missingFrom(SchemaRegistry registry) {
            List<String> missing = new ArrayList<>();
            if (registry != null) {
                for (String id : schemaIds) {
                    if (!registry.has(id)) {
                        missing.add(id);
                    }
                }
            }
            return missing;
        }

        /** Reporting view for {@code ops/packs}; {@code registry} may be null to skip resolution. */
        public Map<String, Object> describe(SchemaRegistry registry) {
            Map<String, Object> out = new LinkedHashMap<>();
            out.put("name", name);
            out.put("namespace", namespace);
            out.put("source", source);
            out.put("version", version);
            out.put("gs08", gs08);
            out.put("aliasOf", aliasOf);
            out.put("transactionType", transactionType);
            out.put("idScope", idScope);
            out.put("schemaCount", schemaCount);
            out.put("structureIndex", structureIndex);
            out.put("core", core());
            List<String> missing = missingFrom(registry);
            out.put("status", missing.isEmpty() ? "active" : "degraded");
            out.put("missingSchemas", missing);
            return out;
        }
    }

    private final List<Pack> packs;

    private PackCatalog(List<Pack> packs) {
        this.packs = List.copyOf(packs);
    }

    public static PackCatalog empty() {
        return new PackCatalog(List.of());
    }

    /** The bundled catalog: {@code packs.json} from the classpath. */
    public static PackCatalog fromClasspath() {
        try (InputStream in = PackCatalog.class.getResourceAsStream("/" + RESOURCE)) {
            if (in == null) {
                LOG.warn("No {} on the classpath — pack reporting will be empty", RESOURCE);
                return empty();
            }
            return parse(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        } catch (IOException | RuntimeException e) {
            LOG.warn("Cannot read {} ({}); pack reporting will be empty", RESOURCE, e.toString());
            return empty();
        }
    }

    /**
     * A catalog from a pack root on disk — the shape a delivered (npm or uploaded) pack
     * will use. Reads {@code <root>/packs.json}.
     */
    public static PackCatalog fromDirectory(Path root) {
        Path file = root == null ? null : root.resolve(RESOURCE);
        if (file == null || !Files.isRegularFile(file)) {
            return empty();
        }
        try {
            return parse(Files.readString(file));
        } catch (IOException | RuntimeException e) {
            LOG.warn("Cannot read {} ({}); ignoring that root", file, e.toString());
            return empty();
        }
    }

    static PackCatalog parse(String json) {
        final JsonElement root;
        try {
            root = GSON.fromJson(json, JsonElement.class);
        } catch (RuntimeException malformed) {
            // Pack reporting is not worth a boot failure (see the class javadoc).
            LOG.warn("{} is not valid JSON ({}); pack reporting will be empty", RESOURCE, malformed.toString());
            return empty();
        }
        if (root == null || !root.isJsonArray()) {
            return empty();
        }
        List<Pack> out = new ArrayList<>();
        for (JsonElement el : root.getAsJsonArray()) {
            if (!el.isJsonObject()) {
                continue;
            }
            JsonObject o = el.getAsJsonObject();
            String name = str(o, "name");
            if (name == null || name.isBlank()) {
                LOG.warn("skipping pack entry with no name: {}", o);
                continue;
            }
            List<String> ids = new ArrayList<>();
            if (o.has("schemaIds") && o.get("schemaIds").isJsonArray()) {
                for (JsonElement id : o.getAsJsonArray("schemaIds")) {
                    ids.add(id.getAsString());
                }
            }
            out.add(new Pack(name, str(o, "namespace"), orDefault(str(o, "source"), "bundled"),
                str(o, "version"), str(o, "gs08"), str(o, "aliasOf"), str(o, "transactionType"),
                str(o, "structureIndex"), str(o, "idScope"),
                o.has("schemaCount") ? o.get("schemaCount").getAsInt() : ids.size(), ids));
        }
        return new PackCatalog(out);
    }

    public List<Pack> packs() {
        return packs;
    }

    public int size() {
        return packs.size();
    }

    /** Total schemas declared across every pack (not the registry's count — builtins differ). */
    public int schemaCount() {
        int n = 0;
        for (Pack p : packs) {
            n += p.schemaCount();
        }
        return n;
    }

    /** The guides packs cover, canonical ids and aliases alike, in manifest order. */
    public List<String> guides() {
        List<String> out = new ArrayList<>();
        for (Pack p : packs) {
            if (p.gs08() != null) {
                out.add(p.gs08());
            }
        }
        return out;
    }

    private static String str(JsonObject o, String key) {
        return o.has(key) && o.get(key).isJsonPrimitive() ? o.get(key).getAsString() : null;
    }

    private static String orDefault(String v, String dflt) {
        return v == null || v.isBlank() ? dflt : v;
    }
}
