openapi: 3.0.3
info:
  x-product-infos:
    # Array of external references to Products (versions of products) involved in the module.
    # the catalog.yml file will in most cases be referenced from `node_modules/hub-store-catalog`
    - $ref: "./node_modules/@auditlogic/product-github-github/catalog.yml#/Product"
  x-impl-name: GitHub
  version: 0.0.0
  title: '@zerobias-org/module-github-github'
  description: GitHub
paths:
  /organizations:
    get:
      tags:
        - organization
      summary: Retrieves organizations for the authenticated user
      operationId: listOrganizations
      x-method-name: list
      parameters:
        - $ref: '#/components/parameters/pageNumberParam'
        - $ref: '#/components/parameters/pageSizeParam'
      responses:
        '200':
          description: List of organizations
          headers:
            link:
              $ref: '#/components/headers/pagedLinkHeader'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
      security:
        - github-token: ["read:org"]
  /organizations/{organizationId}:
    get:
      tags:
        - organization
      summary: Retrieves detailed information about a specific organization
      operationId: getOrganization
      x-method-name: get
      parameters:
        - $ref: '#/components/parameters/organizationId'
      responses:
        '200':
          description: Organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationInfo'
      security:
        - github-token: ["read:org"]
components:
  securitySchemes:
    github-token:
      type: oauth2
      description: Authentication for the GitHub API (actual method is Personal Access Token)
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/oauth/authorize
          tokenUrl: https://github.com/oauth/token
          scopes:
            read:org: Read organization membership and details
            admin:org: Manage organization properties and settings
  parameters:
    pageNumberParam:
      $ref: "./node_modules/@auditmation/types-core/schema/pageNumberParam.yml"
    pageSizeParam:
      $ref: "./node_modules/@auditmation/types-core/schema/pageSizeParam.yml"
    organizationId:
      name: organizationId
      in: path
      required: true
      description: The organization identifier (name or ID)
      schema:
        type: string
        example: github
  headers:
    pagedLinkHeader:
      $ref: "./node_modules/@auditmation/types-core/schema/pagedLinkHeader.yml"
  schemas:
    Organization:
      type: object
      description: GitHub organization basic information
      required:
        - id
        - login
        - url
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the organization
          example: 1
        login:
          type: string
          description: Organization username/login name
          example: github
        url:
          type: string
          format: url
          description: API URL for the organization
          example: https://api.github.com/orgs/github
        reposUrl:
          type: string
          format: url
          description: API URL for organization repositories
          example: https://api.github.com/orgs/github/repos
        avatarUrl:
          type: string
          format: url
          description: URL for organization avatar image
          example: https://github.com/images/error/github_happy.gif
        description:
          type: string
          nullable: true
          description: Organization description
          example: A great organization
    OrganizationInfo:
      allOf:
        - $ref: '#/components/schemas/Organization'
        - type: object
          properties:
            name:
              type: string
              nullable: true
              description: Display name of the organization
              example: GitHub
            company:
              type: string
              nullable: true
              description: Organization company information
            blog:
              type: string
              format: url
              nullable: true
              description: Organization website URL
              example: https://github.com
            location:
              type: string
              nullable: true
              description: Organization location
              example: San Francisco
            email:
              type: string
              format: email
              nullable: true
              description: Organization email address
            twitterUsername:
              type: string
              nullable: true
              description: Organization Twitter username
            publicRepos:
              type: integer
              description: Number of public repositories
              example: 10
            followers:
              type: integer
              description: Number of followers
              example: 20
            following:
              type: integer
              description: Number of accounts following
              example: 0
            createdAt:
              type: string
              format: date-time
              description: When the organization was created
              example: "2008-01-14T04:33:35Z"
            updatedAt:
              type: string
              format: date-time
              description: When the organization was last updated
              example: "2008-01-14T04:33:35Z"
