name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  pull-request:
    uses: zerobias-org/devops/.github/workflows/pull-request-reusable.yml@main
    secrets: inherit
    with:
      run-integration-tests: 'true'
